### PR TITLE
Yes, I cut the middle pin :>

### PR DESCRIPTION
**Pull request by hasufell**
:sob: 

70 switches destroyed. Figured out something is wrong after I assembled with super glue. Removed 70 switches with heat gun one by one... :man_facepalming:  :smile: :rocket:

### CODE REVIEW

**Comment by hasufell** [comment]
For illustration: this is how the pin looks like for cherry mx silent red:

IMG_20210502_145034

And this is how it looks after me messing it up:

IMG_20210502_145058

Technically... you can still use those switches. But it won't be as smooth anymore since the hole is now deformed and the switch pin won't move as smoothly anymore.

**Comment by dpapavas** [comment]
Thank you for the PR and excuse the careless wording that led to this.  I should have been more explicit.  I changed your proposed changes a bit (maintaining your name as author), to put more emphasis on the difference and avoid such accidents in the future.  Let me know if you're not happy with the committed version.

Regarding the use of super glue, I hope you've read my warning in the build guide.  I have a build that was ruined when the super glue I used entered and gummed up the insides of many switches.  Out of curiosity, what kind of glue did you use, how did you apply it and how did you manage to remove the switches without warping or breaking the printed chassis?

**Comment by hasufell** [comment]
> Regarding the use of super glue, I hope you've read my warning in the build guide.

I destroyed about 6 switches by applying too much glue. Then I changed my approach and only used very very little glue at the spot where the switch legs touch the keyboard print. In my experiece (when trying to remove them later), it really is enough glue. It's basically just 4 small drops of glue, so little that almost nothing gets pressed out when inserting the switch.

I used [Ethyl-2-cyanacrylat based super glue](https://www.amazon.de/gp/product/B01L28D5A0/ref=ppx_yo_dt_b_search_asin_title?currency=EUR&ie=UTF8&language=en_GB&psc=1).

> and how did you manage to remove the switches without warping or breaking the printed chassis?

I didn't... it did warp. I struggled a few days with myself considering whether to start a new print. Due to my RSI I already had major pain and cramps from the sanding and was sure I'm not gonna sand again. So in the end I did another clean print and decided to not sand it.

**Comment by hasufell** [comment]
> Right now I'm wiring the matrix and should be done today/tomorrow.

Sorry for hijacking this issue for support purposes again. I'm done wiring the matrix and assembling. I successfully flashed the board and the left keyboard seems to be working. The right board is detected, can be flashed etc, but doesn't react to key presses. I checked that the pins on the molex receive the keypresses and they do (rows and columns). I'm suspecting this just leaves the option that something is wrong with the controller... but if so, why would it be detected and flashable?

**Comment by dpapavas** [comment]
I enabled the "Discussions" tab, (should be right next to the "Pull requests" tab).  If you wouldn't mind, please copy/paste your question there.  This would make such issues easier to keep track of and to find.

**Pull request closed without merging**
